### PR TITLE
Chinese Translation

### PR DESCRIPTION
**Pull request by Lastprismer**

### CODE REVIEW

**Comment by Blockaroz** [comment]
needs goomoire tooltip and bad apple name

**Comment by Lastprismer** [comment]
I don’t know how to translate goomoire's tooltip into Chinese, because the meme is not in Chinese and it has no equivalent cultural meaning. Maybe it would be better to stay in English.

I have no clue if bad apple is inspired by the Bad Apple from the Touhou series. If that’s true, Bad Apple is also spread by its English name in the Chinese community. If you say its exact Chinese translation “坏苹果”, then maybe not many people will know what it is related to.

**Comment by THEREDSTONEBRO** [comment]
Hey, I'm working on the Spanish (MX) localization and just wanted to let you know that translations don't have to be one to one! The spirit of the jokes/puns is more important and if you have to change things around to preserve the feel of the text, by all means go for it. So yeah, if there's no direct translation, make a whole new tooltip or even item name if you have to! 

As for the Bad Apple, yes it is a joke on the Bad Apple from the Touhou series so take whatever action you deem fit.

**Comment by THEREDSTONEBRO** [comment]
If you have any other questions, feel free to ask. Open to discussion about localization and how to tackle certain parts as we used a lot of puns, wordplay and portmamteau which often don't translate well outside of English.

**Comment by Lastprismer** [comment]
All done. As for those English-specific style vocabulary, we mostly create our own versions, because Chinese pays great attention to the content relationship between Chinese characters. In most cases, puns and portmanteau cannot be translated well. But you don’t have to worry about the translation quality, because Calamity (and Catalyst) Chinese is also translated by us.

**Comment by THEREDSTONEBRO** [comment]
Ah I see now. Well, many thanks for the help!

**Pull request merged**
